### ISSUE TITLE
No API found for setting settlement accounts programatically

### ISSUE THREAD

**Issue by subhasisbanik** [bitpay/java-bitpay-client#27]
We have a requirement where we need to set the settlement account programatically but unfortunately I did not find any such neither in the java client nor are there any REST API exposed in the docs.
Is there any option to do so by calling the Bitpay API?

**Comment by pieterpoorthuis** [comment]
Settlement account information can only be updated using the BitPay merchant dashboard (and requires email confirmation).

**Comment by eternitydaemon** [comment]
Will there be any such API in future releases?

**Comment by pieterpoorthuis** [comment]
It's not on our roadmap.

**Comment by subhasisbanik** [comment]
I am assuming that there is no API endpoint even for settlement instruction. Is it correct?

**Comment by pieterpoorthuis** [comment]
That's correct.

The only API endpoint related to settlements is to fetch settlement reports: https://bitpay.com/api#resource-Settlements

**Comment by subhasisbanik** [comment]
Will there be any support for that in future?

**Comment by pieterpoorthuis** [comment]
It's not on our current roadmap. But I can't say whether it will get on the roadmap.
