### ISSUE TITLE
API for fetching transaction fees

### ISSUE THREAD

**Issue by subhasisbanik** [bitpay/java-bitpay-client#28]
I have tried the GET for ledgers in https://bitpay.com/api#resource-Ledgers
but did not find any transaction fees mentioned in the same.
Is there any API for retrieving the transaction fees for an invoice?

**Comment by pieterpoorthuis** [comment]
Transaction fees are written to the ledger, using a separate ledger entry with code 1023

If your merchant account is on the starter plan, then the first transactions will be on 0% and thus have no separate ledger entry.

For more information, see https://bitpay.com/api#reference-Ledger Entry Codes
