### ISSUE TITLE
Mvn package creates an empty java-bitpay-client.jar file

### ISSUE THREAD

**Issue by javier-dsi** [bitpay/java-bitpay-client#30]
Type` mvn package` and see the warning:

> [INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ java-bitpay-client ---
> [WARNING] JAR will be empty - no content was marked for inclusion!
> [INFO] Building jar: /Users/jslopez/Documents/workspace/mgf/java-bitpay-client/target/java-bitpay-client.jar

There is a pull request (#25) to address this problem already. Locally, I moved the files to match maven expected locations to fix the problem. i.e. added src/main/java and src/test/java and move the files to the expected location.

**Comment by pieterpoorthuis** [comment]
I've merged #25. Thanks for the reminder.
