### ISSUE TITLE
Use merchant facade to fetch invoice (if available)

### ISSUE THREAD

**Issue by pieterpoorthuis** [bitpay/java-bitpay-client#31]
The current getInvoice function only uses the public facade. This works for invoices up to 3 days old, but after 3 days invoices can only be retrieved using the merchant facade.

If the merchant facade is present, the getInvoice function should use the merchant facade to fetch invoices:
https://github.com/bitpay/java-bitpay-client/blob/master/src/controller/BitPay.java#L388

**Comment by anbugal** [comment]
Thanks for your contributions Pieter, we are currently working on updating our open source solutions and this issue will be fixed in the next release.
