### ISSUE TITLE
Error: This endpoint does not support the `user` facade

### ISSUE THREAD

**Issue by sirikumara** [bitpay/java-bitpay-client#32]
When we try to create a Bitpay invoice using createInvoice () method, BitPayException is thrown from 25/01/2018. Bitpay object could be loaded by passing key, client name, and Bitpay URL. Exception stack trace is as below. Please advice us to fix this issue.

GET https://test.bitpay.com/tokens?id=<Some ID>
RESPONSE: {"error":"Unauthorized sin"}
POST https://test.bitpay.com/invoices HTTP/1.1
RESPONSE: {"error":"This endpoint does not support the `user` facade"}

**Comment by pieterpoorthuis** [comment]
BitPay's test environment has been reset. Please create a new BitPay account at test.bitpay.com and redo the pairing.

**Comment by sirikumara** [comment]
Ok, Thanks. will try it.
