### ISSUE TITLE
Add ability to set logger level for client instance

### ISSUE THREAD

**Issue by elanmajkrzak** [bitpay/java-bitpay-client#61]
As of now com.bitpay.sdk.Client only has the option of instantiating it's _log member with the debug level.

`private static final BitPayLogger _log = new BitPayLogger(BitPayLogger.DEBUG);`

We would like to not have all of the debug info in our production instance, as the debug logs are quite verbose.

The bitpay client should be able to be instantiated with whatever logging level we choose.

**Comment by anbugal** [comment]
@elanmajkrzak we will add this on the next release

**Comment by anbugal** [comment]
This is updated on the version [4.6.2003](https://github.com/bitpay/java-bitpay-client/releases/tag/v4.6.2003)
Check release notes
