### ISSUE TITLE
misleading java doc?

### ISSUE THREAD

**Issue by karolmalinowski** [bitpay/java-bitpay-client#67]
Is PayoutInstruction amount in BTC or in Payout batch currency?

https://github.com/bitpay/java-bitpay-client/blob/c378b95e96e5a69f7a7cc9f3eef703057d0850fe/src/main/java/com/bitpay/sdk/model/Payout/PayoutInstruction.java#L36

**Comment by anbugal** [comment]
Thanks for your contribution @karolmalinowski 
This issue has been corrected in #68
