### ISSUE TITLE
Token getting disabled while creating invoice through BITPAY

### ISSUE THREAD

**Issue by sandeep18051989** [bitpay/java-bitpay-client#69]
Token getting disabled while creating invoice through BITPAY
![image](https://user-images.githubusercontent.com/27719887/122468731-b2d3a600-cfd9-11eb-9e75-852b091fa0fd.png)

**Comment by sandeep18051989** [comment]
I have a merchant account, so I am sending merchant facade to this method.

**Comment by anbugal** [comment]
Closing because the provided screenshot doesn't belong to this repo
