### ISSUE TITLE
Unable to create Client using private key as plain text in constructor

### ISSUE THREAD

**Issue by AffanHasan** [bitpay/java-bitpay-client#73]
`Client bitpay = new Client(
    Env.Test,
    "[FULL_PATH_TO_THE_PRIVATE_KEY_|OR|_PRIVATE_KEY_AS-PLAIN_TEXT]",
    new Env.Tokens(){{
        pos = "AvJdGrEqTW9HVsJit9zabAnrJabqaQDhWHRacHYgfgxK";
        merchant = "2smKkjA1ACPKWUGN7wUEEqdWi3rhXYhDX6AKgG4njKvj";
        payroll = "9pJ7fzW1GGeuDQfj32aNATCDnyY6YAacVMcDrs7HHUNo";
    }},
    null //Pass a HttpHost object for proxy usage or NULL to ignore
);`

When creating Client using above syntax as mentioned in [https://bitpay.com/integrations/java](url) I am getting following error:
`Logging level set to: OFF
Exception in thread "main" com.bitpay.sdk.BitPayException: failed to deserialize BitPay server response (Config) : failed to process configuration : Private Key file not found
	at com.bitpay.sdk.Client.<init>(Client.java:94)
	at com.wsgc.ecommerce.ws.controllers.CheckoutController.main(CheckoutController.java:115)
`

I am unable to understand why I am getting this error when I am providing the private key plain text why it is referring to the key file instead of using plain-text private key ?

**Comment by anbugal** [comment]
Hi @AffanHasan if you choose plain text when generating the key then you can use it that way but if you choose In File then you can only use it by passing the file path, for security reasons it's not allowed to mix those two methods.

**Comment by AffanHasan** [comment]
Hi @anbugal anbugal thanks for quick assistance following is the screenshot for the setup utility for private key generation and we selected Text option for storing private key.

![image](https://user-images.githubusercontent.com/1730485/132876423-7e47f9c6-9c35-4e28-b160-1196aabeb994.png)

After executing setup utility above I am getting two files "BitPay.config.json" "private_key_test.key"

Below is screenshot of  "BitPay.config.json"
![image](https://user-images.githubusercontent.com/1730485/132877169-2904b69a-b54c-4327-aa34-8d4473ca31b5.png)

And following is "private_key_test.key"

![image](https://user-images.githubusercontent.com/1730485/132877301-92e2e040-8043-473a-ae68-06be4c79aa2a.png)

I am successfully able to create invoices using private key from "BitPay.config.json" file as a plain text for my nodes client
here is the screen shot:
![image](https://user-images.githubusercontent.com/1730485/132877601-427f07cc-8fc0-4c13-b7c3-baf870387a0a.png)

When I am using same credentials in a similar manner for my Java client it is giving me following errors and I am unable to create a JDK based client for BitPay Integration:

![image](https://user-images.githubusercontent.com/1730485/132877814-1e5d704c-d76f-4a96-83b5-4870eb78441e.png)

Please assist in the above issue I am not sure what steps I am missing in configuring the JDK client.

**Comment by anbugal** [comment]
Hi @AffanHasan,

I can see you're using the NodeJs SDK to generate the keys and trying to use them with this SDK, SDKs are not compatible across languages so you have to use the Java config generator.

Please follow the setup guide: https://github.com/bitpay/java-bitpay-client/blob/master/GUIDE.md

**Comment by AffanHasan** [comment]
Thank you @anbugal that resolved the issue.
