### ISSUE TITLE
Facade type "pos/invoice"

### ISSUE THREAD

**Issue by jkolobok** [bitpay/java-bitpay-client#8]
When I create an instance of Bitpay and pass an existing ECkey then it requests tokens and receives token with facade "pos/invoices". Which causes a failure because I'm using facade "pos". 
What does this mean, Why I get it and how to use this?

**Comment by ionux** [comment]
There are general facade tokens, such as the point of sale token you mention, and also resource-level tokens which are used to manipulate specific resources like invoices.  The tokens themselves are stored within the _tokencache hashtable.  If you've already created an invoice then you'll have more than one token in the cache.
